# Generated by Django 3.2.3 on 2021-05-20 08:45

import ckeditor.fields
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(upload_to='career/%Y/%m/%d')),
                ('skills', models.TextField(max_length=1000)),
                ('responsibility', ckeditor.fields.RichTextField()),
                ('apply', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=255)),
                ('last_Name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=500)),
                ('phone_number', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Up to 10 digits allowed.', regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=100)),
                ('employment_Type', models.CharField(max_length=128)),
                ('about', models.TextField(max_length=1000)),
                ('qualify', models.TextField(max_length=1000)),
                ('position', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=60)),
                ('pin_code', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(upload_to='hero/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialSocialHandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.CharField(max_length=50)),
                ('insta', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('photo', models.ImageField(upload_to='team/%Y/%m/%d')),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='testimonal/%Y/%m/%d')),
                ('position', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
